name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Cache SonarCloud
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-cache
        restore-keys: |
          ${{ runner.os }}-sonar-cache

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
        projectKey: ${{ secrets.SONAR_PROJECT_KEY }} 
        organization: ${{ secrets.SONAR_ORGANIZATION }}
